# Generated by Django 5.2 on 2025-04-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('raza', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('raza', 'Raza'), ('edad', 'Edad')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateTimeField()),
                ('en_miniblog', models.BooleanField()),
                ('id_gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.gato')),
            ],
        ),
        migrations.CreateModel(
            name='GatoBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgado', models.DateTimeField()),
                ('id_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.badge')),
                ('id_gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.gato')),
            ],
        ),
        migrations.CreateModel(
            name='FotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.foto')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.chat')),
                ('id_remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='gato',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField()),
                ('id_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.foto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='id_usuario_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_usuario_1', to='cats.usuario'),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_usuario_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_usuario_2', to='cats.usuario'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('good', 'Good'), ('evil', 'Evil')], max_length=4)),
                ('fecha_voto', models.DateTimeField()),
                ('id_foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.foto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.usuario')),
            ],
        ),
    ]
